# Use the official Python 3 image as a parent image
FROM python:3.10-slim

# Set the working directory in the container to /code
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY ./app /code/app
COPY ./worker /code/worker
COPY ./models.py /code/
COPY ./requirements.txt /code/
COPY ./config.py /code/

# Install any dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
